language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rspec
  - bundle exec rubocop

install:
  - gem install bundler
  - sudo apt-get update -qq
  - bundle install